// Code generated by github.com/eduardohumberto/test-gql, DO NOT EDIT.

package model

import (
	"github.com/eduardohumberto/test-gql/example/scalars/external"
)

type Address struct {
	ID       external.ObjectID `json:"id"`
	Location *Point            `json:"location"`
}
